name: Build APK
                                                              on: push
                                                              
                                                              jobs:
                                                                build:
                                                                  runs-on: ubuntu-latest
                                                                  steps:
                                                                  - uses: actions/checkout@v4
                                                                  - run: chmod +x gradlew
                                                                  - run: ./gradlew assembleDebug
                                                                  - uses: actions/upload-artifact@v4
                                                                    with:
                                                                      name: app
                                                                      path: app/build/outputs/apk/debug/*.apk