name: Build Unsigned APKs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build unsigned APKs
        run: ./gradlew assembleDebug

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*-unsigned.apk