- name: Build APKs
                  uses: gradle/gradle-build-action@v3
                  with:
                    arguments: |
                      assembleDebug
                      assembleRelease
                
                - name: Upload APKs as Artifact
                  uses: actions/upload-artifact@v4
                  with:
                    name: all-apks
                    path: |
                      app/build/outputs/apk/release/*-unsigned.apk