name: Android Build
                                                                                
                                                                                on:
                                                                                  push:
                                                                                    branches: [ main ]
                                                                                  pull_request:
                                                                                    branches: [ main ]
                                                                                
                                                                                jobs:
                                                                                  build:
                                                                                    runs-on: ubuntu-latest
                                                                                    
                                                                                    steps:
                                                                                      - name: Checkout code
                                                                                        uses: actions/checkout@v4
                                                                                        
                                                                                      - name: Set up JDK 17
                                                                                        uses: actions/setup-java@v3
                                                                                        with:
                                                                                          java-version: '17'
                                                                                          distribution: 'temurin'
                                                                                          
                                                                                      - name: Build APKs
                                                                                        run: |
                                                                                          chmod +x gradlew
                                                                                          ./gradlew assembleDebug  # Or use your build variant (e.g., `assembleGoogleMatagi`)
                                                                                          
                                                                                      - name: Upload APKs
                                                                                        uses: actions/upload-artifact@v3
                                                                                        with:
                                                                                          name: apk-artifacts
                                                                                          path: app/build/outputs/apk/**/*.apk